"""Add image_file column to Post

Revision ID: 366ac369794a
Revises: 
Create Date: 2026-01-06 19:05:04.240544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '366ac369794a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_file', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###
